# Generated by Django 4.0.6 on 2022-07-25 16:35

import Todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Todo.models.image_file_name),
        ),
    ]
