# Generated by Django 4.0.6 on 2022-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todolist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
