# Generated by Django 4.0.6 on 2022-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='img_format_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
