# Generated by Django 4.0.6 on 2022-07-28 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
